pipeline {
    agent any 
    stages {
        stage("git checkout") {
            steps {
                git credentialsId: 'github', url: 'https://github.com/rameshkumar5155/projects.git'
            }
        }
        stage("build") {
            steps {
                sh "mvn clean package"
                sh "mv target/*.war target/myweb.war"
               }
            }
        stage("deploy-dev") {
            steps {
                sshagent('[tomcat-new'])   {  
                sh """
              
              scp -o StrictHostKeyChecking=no target/myweb.war ec2-user@172.31.45.147:/home/ec2-user/apache-tomcat-9.0.46/webapps/
              ssh ec2-user@172.31.45.147 /home/ec2-user/apache-tomcat-9.0.46/bin/shutdown.sh
              ssh ec2-user@172.31.45.147 /home/ec2-user/apache-tomcat-9.0.46/bin/startup.sh
               """
                }
            }
        }
    }
}

              

